# Generated by Django 4.1.2 on 2022-10-25 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=10)),
                ('descripcion_c', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_d', models.CharField(max_length=20)),
                ('apellido_d', models.CharField(max_length=20)),
                ('rut_d', models.PositiveIntegerField(max_length=9)),
                ('telefono', models.PositiveIntegerField(max_length=9)),
                ('direccion', models.CharField(max_length=30)),
                ('user_d', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_m', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=10)),
                ('patologias', models.TextField(blank=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='veterinaria.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_f', models.CharField(max_length=20)),
                ('apellido_f', models.CharField(max_length=20)),
                ('rut_f', models.PositiveIntegerField(max_length=9)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='veterinaria.cargo')),
                ('user_f', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('date', models.DateTimeField(null=True)),
                ('peluqueria', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='veterinaria.funcionario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='veterinaria.mascota')),
            ],
        ),
    ]
