# Generated by Django 4.1.2 on 2022-10-25 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueno',
            name='rut_d',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rut_f',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
