# Generated by Django 4.1.2 on 2022-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_alter_dueno_rut_d_alter_dueno_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_m',
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre_c',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='apellido_d',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='nombre_d',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='rut_d',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='apellido_f',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nombre_f',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rut_f',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_m',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=30),
        ),
    ]
