# Generated by Django 4.1.2 on 2022-10-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_remove_cargo_id_remove_dueno_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
